name: Run Checkstyle

permissions:
  contents: read

on:
  pull_request:
    types: [ opened, reopened, edited, synchronize ]
    branches:
      - 'main'
env:
  VERSION_NUMBER: $({github.run_number})

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Test
      run: ./gradlew checkstyleMain checkstyleTest
